#!/usr/bin/python
# coding: utf-8
#
# Data manipulator frontend for Omas Mullis
#
# Taavi Ilves, taavi.ilves@gmail.com, 2014

import sys
import argparse
sys.path.append('.')
from manipulation import compile

parser = argparse.ArgumentParser()
parser.add_argument('path', help='path to input CSV')
parser.add_argument('-d', '--debug',
                    help='prints debug messages',
                    action='store_true')
parser.add_argument('-j', '--json',
                    help='path to output json file, will be overwritten')
parser.add_argument('-m', '--mapvid', required=True,
                    help='path to mapvideos or file containing filenames')
parser.add_argument('-s', '--streetvid', required=True,
                    help='path to mapvideos or file containing filenames')
parser.add_argument('-md', '--metadata', required=True,
                    help='path to metadata table CSV')

if len(sys.argv) == 1:
    parser.print_help()
    sys.exit(0)

args = parser.parse_args()
compile(args.path, args.debug, args.json, args.mapvid, args.streetvid,
        args.metadata)
